### ISSUE TITLE
Does it support amount input just like LEAlertController

### ISSUE THREAD

**Issue by guoyingtao** [efremidze/NumPad#4]
Does it support Amount input just like LEAlertController?
Thanks!

**Comment by efremidze** [comment]
No, but its really easy to add.

**Comment by efremidze** [comment]
Sorry, I never added it to this repo. Its pretty easy to add though.

**Comment by guoyingtao** [comment]
Thanks for your answer! I really need this feature. Could you please add it to this repo? Thanks again!

**Comment by efremidze** [comment]
I add the code to the demo and u can copy and paste it?

**Comment by guoyingtao** [comment]
OK, Thanks a lot!

**Comment by efremidze** [comment]
Updated master with the currency number formatter

**Comment by guoyingtao** [comment]
Thank you very much!
